//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kidyx.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactus
    {
        public int Id { get; set; }
        public string map_link { get; set; }
        public string contact_description { get; set; }
        public string Address { get; set; }
        public string phone { get; set; }
        public string Email { get; set; }
    }
}
