//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kidyx.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fosection
    {
        public int Id { get; set; }
        public string picture { get; set; }
        public string heading { get; set; }
        public string details { get; set; }
        public int price { get; set; }
        public int catagory { get; set; }
        public string link { get; set; }
    
        public virtual catagory catagory1 { get; set; }
    }
}
