//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kidyx.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fsection
    {
        public int Id { get; set; }
        public string picture { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string tag { get; set; }
        public string tnum { get; set; }
        public string tcontrol { get; set; }
        public string cat { get; set; }
    }
}
