//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kidyx.com.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<catagory> catagory { get; set; }
        public virtual DbSet<UserProfile_details> UserProfile_details { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<pagedetails> pagedetails { get; set; }
        public virtual DbSet<fsection> fsection { get; set; }
        public virtual DbSet<tsection> tsection { get; set; }
        public virtual DbSet<shoporder> shoporder { get; set; }
        public virtual DbSet<productlist> productlist { get; set; }
        public virtual DbSet<thsection> thsection { get; set; }
        public virtual DbSet<fosection> fosection { get; set; }
        public virtual DbSet<review> review { get; set; }
        public virtual DbSet<fisection> fisection { get; set; }
        public virtual DbSet<Wishlist> Wishlist { get; set; }
        public virtual DbSet<contactus> contactus { get; set; }
    }
}
