//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kidyx.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int Id { get; set; }
        public string user_id { get; set; }
        public int rating { get; set; }
        public string message { get; set; }
        public int product_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual UserProfile_details UserProfile_details { get; set; }
    }
}
