//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kidyx.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public int Id { get; set; }
        public int productid { get; set; }
        public string productname { get; set; }
        public string productpic { get; set; }
        public Nullable<int> productprice { get; set; }
        public string userid { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserProfile_details UserProfile_details { get; set; }
    }
}
